application: udacity-itsoes-wd
version: 5
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: handler.app

- url: /Unit2/.*
  script: unit2.app

- url: /Unit3/.*
  script: unit3.app

- url: /Unit4/.*
  script: unit4.app

- url: /Unit5/.*|/Unit5
  script: unit5.app

- url: /Unit6/.*|/Unit6
  script: unit6.app

#- url: /extendedblog/.*|/extendedblog
#  script: hw5/blog.app

- url: .*
  script: handler.app

libraries:
- name: jinja2
  version: latest